while True:
    print('your data is protected and remains private')
    m = 0
    n = 0
    b = 0
    v = 0
    z = 0
    q = input('name')
    m = q
    w = input('birth year')
    n = w
    e = input('birth month')
    b = e
    r = input('birth day:(1, 2, 3...)')
    v = r
    t = input('last name')
    c = t
    y = input('key word')
    x = y
    u = input('second key word')
    z = u
    print('list creation...')
    from time import sleep
    sleep(2.3)
    print(m + n)
    print(m + '123')
    print(m + '1234')
    print(m + '12345')
    print(m + '4321')
    print(m + '321')
    print(m + '54321')
    print( '1' + m + '2')
    print(n + b)
    print(n + v)
    print(b + n)
    print(b + v)
    print(v + b)
    print(v + n)
    print(n + b + v)
    print(n + v + b)
    print(b + n + v)
    print(b + v + n)
    print(v + b + n)
    print(v + n + b)
    print(m)
    print(n)
    print(b)
    print(v)
    print(m[0] + n)
    print('123' + m)
    print('1234' + m)
    print('12345' + m)
    print('54321' + m)
    print('4321' + m)
    print('321' + m)
    print(m + '01')
    print('aaaaaa')
    print('P@ssword')
    print('p@assword')
    print('PPASSWORD')
    print('password')
    print(m + "'s" + ' password')
    print(m + "'s" + ' Password')
    print(m + "'s" + ' PASSWORD')
    print(m + "'s" + ' P@SSWORD')
    print(m + "'s" + ' p@assword')
    print(m + "'s" + ' P@ssword')
    print(m[0] + n)
    print(c)
    print(m + c)
    print(c + m)
    print(c + n)
    print(n + c)
    print(m + 'pro')
    print('pro' + m)
    print(len(c) + len(m))
    print(len(m) + len(c))
    print(m[0] + n + c[0] + n)
    print(m[0] + n + c[0] + b)
    print(m[0] + n + c[0] + v)
    print(m[0] + b + c[0] + n)
    print(m[0] + b + c[0] + b)
    print(m[0] + b + c[0] + v)
    print(m[0] + v + c[0] + n)
    print(m[0] + v + c[0] + b)
    print(m[0] + v + c[0] + v)
    print(c[0] + n + m[0] + n)
    print(c[0] + n + m[0] + b)
    print(c[0] + n + m[0] + v)
    print(c[0] + b + m[0] + n)
    print(c[0] + b + m[0] + b)
    print(c[0] + b + m[0] + v)
    print(c[0] + v + m[0] + n)
    print(c[0] + v + m[0] + b)
    print(c[0] + v + m[0] + v)
    print(m[0] + n + m[0] + n)
    print(m[0] + n + m[0] + b)
    print(m[0] + n + m[0] + v)
    print(m[0] + b + m[0] + n)
    print(m[0] + b + m[0] + b)
    print(m[0] + b + m[0] + v)
    print(m[0] + v + m[0] + n)
    print(m[0] + v + m[0] + b)
    print(m[0] + v + m[0] + v)
    print(c[0] + n + c[0] + n)
    print(c[0] + n + c[0] + b)
    print(c[0] + n + c[0] + v)
    print(c[0] + b + c[0] + n)
    print(c[0] + b + c[0] + b)
    print(c[0] + b + c[0] + v)
    print(c[0] + v + c[0] + n)
    print(c[0] + v + c[0] + b)
    print(c[0] + v + c[0] + v)
    print(x)
    print(x[0] + m)
    print(x + '123')
    print(x + c)
    print(x + m)
    print(x + '1234')
    print(x + '12345')
    print(x + '123456')
    print('love' + x)
    print(x + 'love')
    print(len(x))
    print(x + n)
    print(n + x)
    print(x + n + b + v)
    print(v + b + n + x)
    print(x[0] + n + x[len(x) - 1])
    print(x + x)
    print(m[0] + n + x[0])
    print(x[0] + n + m[0])
    print(x + 'pro')
    print('password' + x)
    print('password' + m)
    print(x + m)
    print(z)
    print(z[0] + m)
    print(z + '123')
    print(z + c)
    print(z + m)
    print(z + '1234')
    print(z + '12345')
    print(z + '123456')
    print('love' + z)
    print(z + 'love')
    print(len(z))
    print(z + n)
    print(n + z)
    print(z + n + b + v)
    print(v + b + n + z)
    print(z[0] + n + z[len(z) - 1])
    print(z + z)
    print(m[0] + n + z[0])
    print(z[0] + n + m[0])
    print(z + 'pro')
    print('password' + z)
    print('password' + m)
    print(z + m)
    print()
    print('_' * 62)
    

   


